services:
  - type: web
    name: frigopom-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install --include=dev && npm run build
    startCommand: node dist/main
    envVars:
      - key: DB_HOST
        value: ep-frosty-heart-ale13sbj.c-3.eu-central-1.aws.neon.tech
      - key: DB_USER
        value: neondb_owner
      - key: DB_PASS
        value: npg_c0jripgPORA7
      - key: DB_NAME
        value: neondb
      - key: JWT_SECRET
        value: frigopom_secret_2025
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: "*"